### ISSUE TITLE
Checklist 1.0

### ISSUE THREAD

**Issue by denisrosset** [replab/replab#601]
For the release itself

- [ ] Have the help consistent ( `replab_checkhelp` )
- [ ] Verify the cache property issue on Octave 6.3.0
- [ ] Generate the Sphinx documentation and fix warnings
- [ ] Have a cursory look at the Sphinx documentation
- [ ] Add documentation to `PermutationGroup`
- [ ] Verify that every public class is listed in the API (notably MatrixGroup, FiniteGroupType) and that the code structure descriptions are up to date

Update website

- [ ] Front page
- [ ] Go through the development docs, update
- [ ] Publication list
- [ ] Advertise technical achievements
- [ ] Tuto for quantum info -> tuto for physicists (singlet vs triplet)
- [ ] Clean up issues, move "big projects" to dedicated repo
- [ ] Add "make a tutorial" first issues
